// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZM9_dqJdhQYD-qre42TK10fvBiHVdtz0',
    appId: '1:429702531295:web:56279a396e6eb7ea84816a',
    messagingSenderId: '429702531295',
    projectId: 'mascotas-1ee56',
    authDomain: 'mascotas-1ee56.firebaseapp.com',
    storageBucket: 'mascotas-1ee56.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmH4LgrpLsjb6EP8Avl8F-faPdTyh9P30',
    appId: '1:429702531295:android:a1007178ccafdcde84816a',
    messagingSenderId: '429702531295',
    projectId: 'mascotas-1ee56',
    storageBucket: 'mascotas-1ee56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJkMNhbakS1ojKR8IxcEbTT2c_Z2nW6aY',
    appId: '1:429702531295:ios:89a099b2788e208d84816a',
    messagingSenderId: '429702531295',
    projectId: 'mascotas-1ee56',
    storageBucket: 'mascotas-1ee56.firebasestorage.app',
    iosBundleId: 'com.example.fireCrud5a25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZM9_dqJdhQYD-qre42TK10fvBiHVdtz0',
    appId: '1:429702531295:web:a77b5ddc5ed383d784816a',
    messagingSenderId: '429702531295',
    projectId: 'mascotas-1ee56',
    authDomain: 'mascotas-1ee56.firebaseapp.com',
    storageBucket: 'mascotas-1ee56.firebasestorage.app',
  );
}
